bilans/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'bilans'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('canvas/', login_required(views.index), name='list_canvas'),
    path('canvas/add/', login_required(views.CanvaCreateView.as_view()), name='add_canvas'),
    path('canvas/edit/<int:pk>/', login_required(views.CanvaDetailView.as_view()), name='canva_detail'),
    path('canvas/<int:pk>/bilan/edit/', login_required(views.BilansEditView.as_view()), name='bilan_edit'),
    path('canvas/<int:pk>/autre/edit/', login_required(views.AutresEditView.as_view()), name='autre_edit'),
    path('canvas/<int:pk>/tresorerie/edit/', login_required(views.TresoreriesEditView.as_view()), name='tresorerie_edit'),
    path('canvas/<int:pk>/production/edit/', login_required(views.ProductionsEditView.as_view()), name='production_edit'),
    path('canvas/<int:pk>/validation/edit/', login_required(views.CheckboxsEditView.as_view()), name='canva_valid'),
    path('canva/excelpage/', views.ExcelPageView.as_view(), name='excelpage'), 
   
    path('canvas/edit/bilanexport/<int:pk>', views.export_bilans_xls, name='bilan_excel'),
    path('canvas/consult/sommeexport/<int:pk>', views.export_somme_xls, name='somme_excel'),
    
    
    
    path('canvas/consult/<int:pk>/', login_required(views.CanvaConsultlView.as_view()), name='canva2_detail'),
   
    
   path('canvas/list2/', login_required(views.index2), name='list2_canvas'),
    
    
  


    
    
            
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from bilans import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bilans.urls', namespace='bilans')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('', include('registration.backends.simple.urls')),
    
    
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

bilans/forms.py
from django.forms.models import inlineformset_factory
from .models import Canva, Bilan, Autre, Tresorerie, Production, Checkbox
from django import forms
from django.forms import ModelForm

CheckboxsFormset= inlineformset_factory(Canva, Checkbox, fields=('validation',), can_delete=False,max_num=1,
                                        widgets = {
                                            'validation' : forms.CheckboxInput(attrs={'style': 'width:40px;height:40px;'}),
                                        },
                                       
                                            
                                      labels = {"validation" : ""},
                                      
                                                )


BilansFormset = inlineformset_factory(Canva, Bilan, fields=('agregat', 'SCF', 'mois1', 'mois2'), can_delete=False, max_num=26, min_num=26,
    
                                         widgets = {
                                            'agregat' : forms.TextInput(attrs={'class': 'col-sm-3'}),
                                            'SCF' : forms.TextInput(attrs={'class': 'col-sm-1'}),
                                            'mois1' : forms.NumberInput(attrs={'class': 'col-sm-1'}),
                                            'mois2' : forms.NumberInput(attrs={'class': 'col-sm-1'}),            
                                            
                                            
                                            },
                                            
                                            
                                      labels = {"agregat": "", "SCF": "", "mois1": "", "mois2": ""},
                                       
                                                )

    
AutresFormset = inlineformset_factory(Canva, Autre, fields=('autreag', 'SCF', 'finmoisn1', 'finmoisn','observation'), can_delete=False, max_num=14, min_num=14,  widgets = {
                                            'autreag' : forms.TextInput(attrs={'class': 'col-sm-2'}),
                                            'SCF' : forms.TextInput(attrs={'class': 'col-sm-1'}),
                                            'finmoisn1' : forms.NumberInput(attrs={'class': 'col-sm-2'}),
                                            'finmoisn' : forms.NumberInput(attrs={'class': 'col-sm-2'}),
                                            'observation' : forms.TextInput(attrs={'class': 'col-sm-4'}),
                                            }, labels = {"autreag": "", "SCF": "", "finmoisn1": "", "finmoisn": "", "ecart": "", "evolution": "", "observation": ""},
                                                )


TresoreriesFormset = inlineformset_factory(Canva, Tresorerie, fields=('SCF', 'banques', 'moism1', 'moism', 'observation'), can_delete=False, max_num=11, min_num=11, widgets = {
                                            'SCF' : forms.TextInput(attrs={'class': 'col-sm-1'}),
                                            'banques' : forms.TextInput(attrs={'class': 'col-sm-4'}),
                                            'moism1' : forms.NumberInput(attrs={'class': 'col-sm-1'}),
                                            'moism' : forms.NumberInput(attrs={'class': 'col-sm-1'}),
                                            'observation' : forms.TextInput(attrs={'class': 'col-sm-4'}),
                                            }, labels = {"SCF": "", "banques": "", "moism1": "", "moism": "", "observation": ""},
                                                )


ProductionsFormset = inlineformset_factory(Canva, Production, fields=('produit', 'unité', 'mois1', 'mois2'), can_delete=False, max_num=23, min_num=23, widgets = {
                                            'produit' : forms.TextInput(attrs={'class': 'col-sm-3'}),
                                            'unité' : forms.TextInput(attrs={'class': 'col-sm-1'}),
                                            'mois1' : forms.NumberInput(attrs={'class': 'col-sm-2'}),
                                            'mois2' : forms.NumberInput(attrs={'class': 'col-sm-2'}),   
                                            }, labels = {"produit": "", "unité": "", "mois1": "", "mois2": ""},
                                                )

bilans/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView, CreateView, DetailView, FormView)
from . models import Canva, Bilan, Autre, Tresorerie, Production, Checkbox
from django.contrib import messages
from django.views.generic.detail import SingleObjectMixin
from django.urls import reverse
from .forms import BilansFormset, AutresFormset, TresoreriesFormset, ProductionsFormset, CheckboxsFormset
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from .decorators import allowed_users
from django.utils import timezone
import xlwt
from xlutils.copy import copy # http://pypi.python.org/pypi/xlutils
from xlrd import open_workbook # http://pypi.python.org/pypi/xlrd
import os
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, Border, Side, PatternFill, Protection
from openpyxl.utils import get_column_letter


def export_bilans_xls(request, pk):    
   
    bilan_queryset = Bilan.objects.filter(canva_id=pk)
    
    
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',)
    for c in Canva.objects.filter(id=pk):
        s = c.site
        d = c.mois      
        a = c.année

    response['Content-Disposition'] = 'attachment; filename=Agregats Mensuels - {site} - {mois} - {année}.xlsx'.format(site=s, mois=d, année=a)

    workbook = Workbook()
    
    worksheet = workbook.active
    worksheet.title = 'TB SCF Ecofie'
    
    
    
    
    for c in Canva.objects.filter(id=pk):
        columns = ['N°', 'Agregat', 'SCF', c.mois+' '+'\n'+str(c.année-1), c.mois+' '+str(c.année), 'Ecart en Valeur', '% evolution', 'a la fin '+c.mois+' '+ str(c.année-1), 'a la fin '+c.mois+' '+ str(c.année), 'Ecart en Valeur', '% evolution']

    row_num = 7
    
    for col_num, column_title in enumerate(columns, 1):
        cell = worksheet.cell(row=row_num, column=col_num)
        cell.value = column_title
        cell.border = Border(top=Side(border_style='thick'), left=Side(border_style='thick'), right=Side(border_style='thick'), bottom=Side(border_style='thick'))
        cell.alignment = Alignment('center') 
        cell.fill = PatternFill(start_color="0099ccff", end_color=("0099ccff"), fill_type='solid')
        cell.font = Font(name='Calibri', bold=True)
        
    n = 0
    for b in bilan_queryset:
        row_num += 1
        n=n+1
        
        if b.mois2 is None:
            b.mois2=0
        if b.mois1 is None:
            b.mois1=0
            row = [n,
                b.agregat, 
                b.SCF, 
                b.mois1,
                b.mois2,
                b.mois2-b.mois1, 
                100, 
                b.finmois1, 
                b.finmois2, 
                b.ecart2, 
                b.evolution2,]
    
            for col_num, cell_value in enumerate(row, 1):
                cell = worksheet.cell(row=row_num, column=col_num)
                cell.value = cell_value
                cell.border = Border(bottom=Side(border_style='medium'), left=Side(border_style='thick'), top=Side(border_style='medium'), right=Side(border_style='thick'))
                cell.alignment = Alignment('center')  
                 
            
                if cell.value is None:
                    cell.value=0
        
        else:
            
            row = [n,
                b.agregat, 
                b.SCF, 
                b.mois1, 
                b.mois2,
                b.mois2-b.mois1, 
                (b.mois2-b.mois1)/b.mois1*100, 
                b.finmois1, 
                b.finmois2, 
                b.ecart2, 
                b.evolution2,]
    
            for col_num, cell_value in enumerate(row, 1):
                cell = worksheet.cell(row=row_num, column=col_num)
                cell.value = cell_value
                cell.border = Border(bottom=Side(border_style='medium'), left=Side(border_style='thick'), top=Side(border_style='medium'), right=Side(border_style='thick'))
                cell.alignment = Alignment('center')    
            
                if cell.value is None:
                    cell.value=0
                    
    
    
    
    
    top = worksheet.cell (row=1, column=2)
    top.value = "TABLEAU DE BORD MENSUEL"
    top.font = Font(name='Calibri', bold=True, size=20, color='000000ff')

    b = 6
    for i in range(14,34):
        ag = worksheet.cell (row=i, column=1)
        ag.value = b
        b = b+1
    
    
    
    
    
    

    
    
    
    
    top2 = worksheet.cell (row=1, column=8)
    for c in Canva.objects.filter(id=pk):
        top2.value = c.mois
        top2.font = Font(name='Calibri', bold=True, size=20)
    
    top3 = worksheet.cell (row=1, column=10)
    for c in Canva.objects.filter(id=pk):
        top3.value = c.année
        top3.font = Font(name='Calibri', bold=True, size=20)
    
    top4 = worksheet.cell (row=3, column=2)
    top4.value = "Groupe"
    top4.border = Border(bottom=Side(border_style='thick'), left=Side(border_style='thick'), top=Side(border_style='thick'), right=Side(border_style='thick'))
    top4.font = Font(name='Calibri', bold=True, size=13)
    top4.alignment = Alignment(horizontal='center')
    
    top5 = worksheet.cell (row=4, column=2)
    top5.value = "EPE"
    top5.alignment = Alignment(horizontal='center')
    top5.border = Border(left=Side(border_style='thick'), bottom=Side(border_style='thick'), right=Side(border_style='thick'))
    top5.font = Font(name='Calibri', bold=True, size=13)
    
    top6 = worksheet.cell (row=3, column=5)
    top6.value = "IMETAL"
    top6.border = Border(bottom=Side(border_style='thick'), top=Side(border_style='thick'))
    top6.font = Font(name='Calibri', bold=True, size=13, color='000000ff')
    
    top7 = worksheet.cell (row=4, column=5)
    top7.value = "ANABIB"
    top7.border = Border(bottom=Side(border_style='thick'))
    top7.font = Font(name='Calibri', bold=True, size=13, color='000000ff')
    
    top8 = worksheet.cell (row=5, column=10)
    top8.value = "En millions de DA"
    top8.font = Font(name='Calibri', bold=True, size=13, color='00ff0000')
    
    vide1 = worksheet.cell (row=3, column=3)
    vide1.border = Border(bottom=Side(border_style='thick'), top=Side(border_style='thick'))
    vide2 = worksheet.cell (row=3, column=4)
    vide2.border = Border(bottom=Side(border_style='thick'), top=Side(border_style='thick'))
    vide3 = worksheet.cell (row=3, column=6)
    vide3.border = Border(bottom=Side(border_style='thick'), top=Side(border_style='thick'), right=Side(border_style='thick'))
    vide4 = worksheet.cell (row=4, column=3)
    vide4.border = Border(bottom=Side(border_style='thick'))
    vide5 = worksheet.cell (row=4, column=4)
    vide5.border = Border(bottom=Side(border_style='thick'))
    vide6 = worksheet.cell (row=4, column=6)
    vide6.border = Border(bottom=Side(border_style='thick'), right=Side(border_style='thick'))
    
    
    
    
    
    
    
    
    column_letter = get_column_letter(1)
    column_dimensions = worksheet.column_dimensions[column_letter]
    column_dimensions.width = 5
    
    
    column_letter = get_column_letter(2)
    column_dimensions = worksheet.column_dimensions[column_letter]
    column_dimensions.width = 45
    
    column_letter = get_column_letter(3)
    column_dimensions = worksheet.column_dimensions[column_letter]
    column_dimensions.width = 13
    
    for i in range(4,12):
        column_letter = get_column_letter(i)
        column_dimensions = worksheet.column_dimensions[column_letter]
        column_dimensions.width = 17
    
    column_letter = get_column_letter(8)
    column_dimensions = worksheet.column_dimensions[column_letter]
    column_dimensions.width = 20
    
    column_letter = get_column_letter(9)
    column_dimensions = worksheet.column_dimensions[column_letter]
    column_dimensions.width = 20
    
    
    
    for i in range(8,34):
        ag = worksheet.cell (row=i, column=2)
        ag.alignment = Alignment('left')
    
    
    
    ind1 = worksheet.cell (row=20, column=2)
    ind1.alignment = Alignment(indent=2)
    
    ind2 = worksheet.cell (row=21, column=2)
    ind2.alignment = Alignment(indent=5)
    
    ind3 = worksheet.cell (row=22, column=2)
    ind3.alignment = Alignment(indent=5)
    
    worksheet.merge_cells('A13:A14')
    merged1 = worksheet['A13']
    merged1.value = "6"
    merged1.alignment = Alignment(horizontal="center", vertical="center")
    
    worksheet.merge_cells('A6:A7')
    merged2 = worksheet['A6']
    merged2b = worksheet['A7']
    merged2.value = 'N°'
    merged2.alignment = Alignment(horizontal="center", vertical="center")
    merged2.border =  Border(top=Side(border_style='thick'), left=Side(border_style='thick'), right=Side(border_style='thick'), bottom=Side(border_style='thick'))
    merged2b.border =  Border(top=Side(border_style='thick'), left=Side(border_style='thick'), right=Side(border_style='thick'), bottom=Side(border_style='thick'))
    merged2.fill = PatternFill(start_color="0099ccff", end_color=("0099ccff"), fill_type='solid')
    merged2.font = Font(name='Calibri', bold=True, size=13)
    
    worksheet.merge_cells('B6:B7')
    merged3 = worksheet['B6']
    merged3b = worksheet['B7']
    merged3.value = 'AGREGATS'
    merged3.alignment = Alignment(horizontal="center", vertical="center")
    merged3.border =  Border(top=Side(border_style='thick'), left=Side(border_style='thick'), right=Side(border_style='thick'), bottom=Side(border_style='thick'))
    merged3b.border =  Border(top=Side(border_style='thick'), left=Side(border_style='thick'), right=Side(border_style='thick'), bottom=Side(border_style='thick'))
    merged3.fill = PatternFill(start_color="0099ccff", end_color=("0099ccff"), fill_type='solid')
    merged3.font = Font(name='Calibri', bold=True, size=13)
    
    worksheet.merge_cells('C6:C7')

bilans/templates/canva_consulter.html
{% extends 'base.html' %}
{% load auth_extras %}

{% block title %}{{ canva.name }}{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
		<li class="nav-item active">
        <a class="nav-link" href="{% url 'bilans:list2_canvas' %}"><button class="btn btn-danger">Retour a la List</button></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bilans:home' %}"><button class="btn btn-danger">Retour a La page D'accueil</button></a>
      </li>
	</ul>
</div>
</nav>

CONSULTATION
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	
	<h3>AGREGATS MONSUELS</h3>
	<div class="d-flex d-flex-inline">
		<span class="pe-2"><h5>CANVA</h5></span> 
		<h5>{{ canva.mois }} {{ canva.année }}</h5>
	</div>

<div class="btn btn-primary w-100 mb-3">BILAN MONSUEL</div>

<br />
<br /><br />
<br /><br />
<br />	


<center><a href="{% url 'bilans:somme_excel' canva.pk %}" role="button" class="btn btn-secondary w-50 mb-50"><h1>Somme des Agregats de {{ canva.mois }} {{ canva.année }}</h1></a></center>



<br />
<br />
{% endblock content %}

bilans/templates/canva_create.html
{% extends 'base.html' %}
{% load auth_extras %}

{% block title %}Nouveau Canvas{% endblock %}

{% block content %}

	<form action="" method="post">
		{% for hidden_field in form.hidden_fields %}
			{{ hidden_field.error }}
			{{ hidden_field }}
		{% endfor %}
		
		{% csrf_token %}
		
		{{ form.non_form_errors }}
		<ul class="list-group">
		{% for field in form %}
			{{ field.errors }}
		<center><li class="list-group-item">{{ field.label_tag }}	{{ field }}</li></center>		
		</ul>
		{% endfor %}
		
		<p class="pt-2">
			<button type="submit" class="btn btn-primary w-100 mb-2">Ajouter Canvas</button>
			<a href="{% url 'bilans:home' %}" role="button" class="btn btn-secondary w-100">Annuler</a>
		</p>
{% endblock content %}

bilans/templates/canva_detail.html
{% extends 'base.html' %}
{% load auth_extras %}

{% block title %}{{ canva.name }}{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
	<li class="nav-item active">
        <a class="nav-link" href="{% url 'bilans:list_canvas' %}"><button class="btn btn-danger">Retour a la List Canvas</button></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bilans:home' %}"><button class="btn btn-danger">Retour a La Page D'Accueil</button></a>
      </li>
	</ul>
</div>
</nav>

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	
	<center><h3>AGREGATS MONSUELS</h3></center>
	<center><h3>{{ canva.site }} {{ canva.mois }} {{ canva.année }}</h3></center>
	<hr>

<p>
		<a href="{% url 'bilans:bilan_edit' pk=canva.pk %}" role="button" class="btn btn-primary w-100 mb-2">Editer BILAN</a>
		<a href="{% url 'bilans:autre_edit' pk=canva.pk %}" role="button" class="btn btn-primary w-100 mb-2">Editer AUTRES AGREGATS</a>
		<a href="{% url 'bilans:tresorerie_edit' pk=canva.pk %}" role="button" class="btn btn-primary w-100 mb-2">Editer TRESORERIE</a>
		<a href="{% url 'bilans:production_edit' pk=canva.pk %}" role="button" class="btn btn-primary w-100 mb-2">Editer PRODUCTION</a>
		<a href="{% url 'bilans:bilan_excel' canva.pk %}" role="button" class="btn btn-secondary w-100">exporter vers excel</a>
</p>
		{% if request.user|has_group:"CDG" %}
		<p>	
		<a href="{% url 'bilans:canva_valid' pk=canva.pk %}" role="button" class="btn btn-info w-100 mb-2">VALIDER</a>
		</p>
		{% endif %}
{% endblock content %}

bilans/templates/canva_list.html
{% extends 'base.html' %}
{% load auth_extras %}
  
{% block title %}CANVAS{% endblock %}
<p>{% block content %}</p>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bilans:home' %}"><button class="btn btn-danger">Retour</button></a>
      </li>
	</ul>
</div>
</nav>


<center><div class="btn btn-primary w-80 mb-2"><h1>Canvas Monsuels EDITION</h1></div></center>


<table width="1471" height="519" border="1">
  <tbody>
    <tr bgcolor="#17ABB0" border="1">
      <th width="248" height="59" style="text-align: center" scope="col"><h1><em><strong>DG</strong></em></h1></th>
      <th width="237" scope="col"><em>
      <h1><strong> ALTUMET</strong></h1></em></th>
      <th width="267" style="text-align: center" scope="col"><em><h1><strong>IRRAGRIS</strong></h1></em></th>
      <th width="224" style="text-align: center" scope="col"><em><h1><strong>PAF</strong></h1></em></th>
      <th width="222" style="text-align: center" scope="col"><em><h1><strong>PTS</strong></h1></em></th>
      <th width="233" style="text-align: center" scope="col"><em><h1><strong>PTTP</strong></h1></em></th>
    </tr>
    <tr>
      <td><p>{% if DG %}</p>
       {% if request.user|has_group:"DG" %} 
	   <ul class="list-unstyled">
          {% for c in DG %}
		  {% if now >= c.created %}
          <li>
		  <center>
              <a class="btn btn-info btn-outline-dark w-30 mb-1" href="{{ c.get_absolute_url }}">{{ c.mois }}	---	{{ c.année }} </a>
            </center>
			</li>
          {% endif %} 
          {% endfor %}
        {% endif %}
		</ul>
		{% endif %} </td>
      <td><p>{% if ALTUMET %}
        </p>
		{% if request.user|has_group:"ALTUMET" %} 
        <ul class="list-unstyled">
          {% for c in ALTUMET %}
		  {% if now >= c.created  %}
          <li>
            <center>
              <a class="btn btn-info btn-outline-dark w-30 mb-1" href="{{ c.get_absolute_url }}">{{ c.mois }}	---	{{ c.année }}</a>
            </center>
			{% endif %}
          </li>
          {% endfor %}
        </ul>
		{% endif %}
{% else %}
<p>il n y a pas de Canvas.</p>
{% endif %}</td>
      <td><p>{% if IRRAGRIS %}
        </p>
		{% if request.user|has_group:"IRRAGRIS" %}
        <ul class="list-unstyled">
          {% for c in IRRAGRIS %}
		  {% if now >= c.created %}
          <li>
            <center>
              <a class="btn btn-info btn-outline-dark w-30 mb-1" href="{{ c.get_absolute_url }}">{{ c.mois }}	---	{{ c.année }}</a>
            </center>
			{% endif %}
          </li>
          {% endfor %}
        </ul>
		{% endif %}
{% else %}
<p>il n y a pas de Canvas.</p>
{% endif %}</td>
      <td><p>{% if PAF %}
        </p>
		{% if request.user|has_group:"PAF" %}
        <ul class="list-unstyled">
          {% for c in PAF %}
		  {% if now >= c.created %}
          <li>
            <center>
              <a class="btn btn-info btn-outline-dark w-30 mb-1" href="{{ c.get_absolute_url }}">{{ c.mois }}	---	{{ c.année }}</a>
            </center>
			{% endif %}
          </li>
          {% endfor %}
        </ul>
		{% endif %}
{% else %}
<p>il n y a pas de Canvas.</p>
{% endif %}</td>
      <td><p>{% if PTS %}
        </p>
		{% if request.user|has_group:"PTS" %}
        <ul class="list-unstyled">
          {% for c in PTS %}
		  
		  {% if now >= c.created %}
		  
          <li>
            <center>
              <a class="btn btn-info btn-outline-dark w-30 mb-1" href="{{ c.get_absolute_url }}">{{ c.mois }}	---	{{ c.année }}</a>
            </center>
			{% endif %}
          </li>
          {% endfor %}
        </ul>
		{% endif %}
{% else %}
<p>il n y a pas de Canvas.</p>
{% endif %}</td>
<td><p>{% if PTTP %}
        </p>
{% if request.user|has_group:"PTTP" %}
   <ul class="list-unstyled">   
        
          {% for c in PTTP %}
		  {% if now >= c.created %}
        <li>  
            <center>
              <a class="btn btn-info btn-outline-dark w-30 mb-1" href="{{ c.get_absolute_url }}">{{ c.mois }}	---	{{ c.année }}</a>
            </center>
			
		</li>
          {% endif %}
          {% endfor %}
        </ul>
{% else %}
<p>il n y a pas de Canvas.</p>
{% endif %}</td>{% endif %}
    </tr>
  </tbody>
</table>

<HR>
<BR />

{% endblock content %}

bilans/templates/canva_list2.html
{% extends 'base.html' %}
{% load auth_extras %}
  
{% block title %}CANVAS{% endblock %}
<p>{% block content %}</p>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bilans:home' %}"><button class="btn btn-danger">Retour</button></a>
      </li>
	</ul>
</div>
</nav>


<center><div class="btn btn-primary w-80 mb-2"><h1>Canvas Monsuels EDITION</h1></div></center>


<table width="1471" height="519" border="1">
  <tbody>
    <tr bgcolor="#17ABB0" border="1">
      <th width="248" height="59" style="text-align: center" scope="col"><h1><em><strong>Sommes Agregats Mensuels</strong></em></h1></th>
    </tr>
    <tr>
      <td><p>{% if DG %}</p>
	   <ul class="list-unstyled">
          {% for c in DG %}
		  {% if now >= c.created %}
          <li>
		  <center>
              <a class="btn btn-info btn-outline-dark w-30 mb-1" href='/canvas/consult/{{c.pk}}'>{{ c.mois }}	---	{{ c.année }} </a>
            </center>
			</li>
          {% endif %} 
          {% endfor %}
        
		</ul>
		{% endif %} </td></tr>
  </tbody>
</table>

<HR>
<BR />

{% endblock content %}

bilans/templates/home.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load static %}

{% block title %}Page d'accueil{% endblock %}

{% block content %}

{% if request.user.is_authenticated %}

	
		
	
	<h1><center>Agregats Mensuels</center></h1>
	
	<hr>
	
	<center>
	<a href="{% url 'bilans:list_canvas' %}" role="button" class="btn btn-primary w-50 mb-2">EDITER Agregats mensuels</a>
	<a href="{% url 'bilans:list2_canvas' %}" role="button" class="btn btn-primary w-50 mb-2">Sommes Agregats mensuels</a>
	{% if request.user|has_group:"admin" %}
	<a href="{% url 'bilans:add_canvas' %}" role="button" class="btn btn-secondary w-50">Ajouter Canvas</a>
	{% endif %}
	</center>
{% else %}
	<center><h1>veuillez vous connecter</h1></center>
{% endif %}






{% endblock content %}